In [1]:
import numpy as np
from sklearn import datasets
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.np_utils import to_categorical
from keras.optimizers import Adam

In [2]:
iris = datasets.load_iris()
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [3]:
iris.target[:3]

array([0, 0, 0])

In [6]:
model = Sequential()

model.add(Dense(8, activation='relu', input_dim=4))
model.add(Dense(12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax')) # 0: setosa, 1: versicolor, 2: virginica

opt = Adam(learning_rate = 0.001)

model.compile(
    optimizer=opt, 
    loss='categorical_crossentropy',
    metrics = ['accuracy']
)

In [7]:
X_train = iris.data
y_train = to_categorical(iris.target)

In [8]:
shuffle = np.random.permutation(y_train.shape[0])
X_train = X_train[shuffle]
y_train = y_train[shuffle]

In [9]:
model.fit(
    X_train[:-3],
    y_train[:-3],
    epochs = 100,
    validation_split = 0.35
)

Epoch 1/100
3/3 [==============================] - 1s 119ms/step - loss: 1.1946 - accuracy: 0.3474 - val_loss: 1.1157 - val_accuracy: 0.3654
Epoch 2/100
3/3 [==============================] - 0s 12ms/step - loss: 1.1612 - accuracy: 0.4000 - val_loss: 1.0916 - val_accuracy: 0.5577
Epoch 3/100
3/3 [==============================] - 0s 13ms/step - loss: 1.1368 - accuracy: 0.5684 - val_loss: 1.0796 - val_accuracy: 0.6923
Epoch 4/100
3/3 [==============================] - 0s 13ms/step - loss: 1.1222 - accuracy: 0.6316 - val_loss: 1.0724 - val_accuracy: 0.7115
Epoch 5/100
3/3 [==============================] - 0s 14ms/step - loss: 1.1142 - accuracy: 0.6316 - val_loss: 1.0669 - val_accuracy: 0.7115
Epoch 6/100
3/3 [==============================] - 0s 12ms/step - loss: 1.1052 - accuracy: 0.6211 - val_loss: 1.0630 - val_accuracy: 0.6923
Epoch 7/100
3/3 [==============================] - 0s 11ms/step - loss: 1.0967 - accuracy: 0.6105 - val_loss: 1.0598 - val_accuracy: 0.6731
Epoch 8/100
3/3 [==

3/3 [==============================] - 0s 12ms/step - loss: 0.7109 - accuracy: 0.8947 - val_loss: 0.6726 - val_accuracy: 0.9423
Epoch 60/100
3/3 [==============================] - 0s 12ms/step - loss: 0.6976 - accuracy: 0.9053 - val_loss: 0.6610 - val_accuracy: 0.9615
Epoch 61/100
3/3 [==============================] - 0s 11ms/step - loss: 0.6849 - accuracy: 0.9053 - val_loss: 0.6473 - val_accuracy: 0.9615
Epoch 62/100
3/3 [==============================] - 0s 13ms/step - loss: 0.6728 - accuracy: 0.9053 - val_loss: 0.6350 - val_accuracy: 0.9615
Epoch 63/100
3/3 [==============================] - 0s 12ms/step - loss: 0.6607 - accuracy: 0.9053 - val_loss: 0.6209 - val_accuracy: 0.9615
Epoch 64/100
3/3 [==============================] - 0s 10ms/step - loss: 0.6489 - accuracy: 0.9053 - val_loss: 0.6101 - val_accuracy: 0.9615
Epoch 65/100
3/3 [==============================] - 0s 11ms/step - loss: 0.6368 - accuracy: 0.9053 - val_loss: 0.5970 - val_accuracy: 0.9615
Epoch 66/100
3/3 [========

In [10]:
X_predict = X_train[-3:]
y_predict = y_train[-3:]

#np.set_printoptions(suppress=True)
output = (model.predict(X_predict) > 0.5).astype("int32")

print("")
print(f"Expected:\n {y_predict}")
print("Actual:\n ", output)

1/1 [==============================] - 0s 68ms/step

Expected:
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
Actual:
  [[1 0 0]
 [0 1 0]
 [1 0 0]]
